"""OpenTelemetry bootstrap: tracing and metrics provider initialisation.

Call ``configure_telemetry()`` once at application startup.  When
``settings.OTEL_ENABLED`` is ``False`` the global SDK providers remain as
built-in no-ops, so instrumented libraries emit nothing and no exporters are
initialised — safe for tests and local troubleshooting.

Call ``shutdown_telemetry()`` during application teardown to flush pending
spans/metrics and release exporter resources.
"""

from __future__ import annotations

import structlog
from fastapi import FastAPI, Response
from opentelemetry import metrics, trace
from opentelemetry.propagate import set_global_textmap
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.semconv.resource import ResourceAttributes
from opentelemetry.trace.propagation.tracecontext import TraceContextTextMapPropagator
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest  # type: ignore[import-not-found]

from app.core.config import settings

logger = structlog.get_logger(__name__)

# Module-level references kept for shutdown; None when telemetry is disabled.
_tracer_provider: TracerProvider | None = None
_meter_provider: MeterProvider | None = None

_EXTRACTION_REQUESTS = Counter(
    "sentiment_extraction_requests_total",
    "Total extraction pipeline executions by terminal status.",
    ["status"],
)
_EXTRACTION_DURATION = Histogram(
    "sentiment_extraction_duration_seconds",
    "Extraction pipeline duration in seconds by terminal status.",
    ["status"],
)
_EXTRACTION_TAGS_SAVED = Counter(
    "sentiment_extraction_tags_saved_total",
    "Total number of extracted tags persisted successfully.",
)
_GENERATION_REQUESTS = Counter(
    "sentiment_generation_requests_total",
    "Total generation pipeline executions by terminal status.",
    ["status"],
)
_GENERATION_DURATION = Histogram(
    "sentiment_generation_duration_seconds",
    "Generation pipeline duration in seconds by terminal status.",
    ["status"],
)
_SCHEDULER_RUNS = Counter(
    "sentiment_scheduler_runs_total",
    "Total scheduler fan-out runs by terminal status.",
    ["status"],
)
_SCHEDULER_DURATION = Histogram(
    "sentiment_scheduler_duration_seconds",
    "Scheduler fan-out duration in seconds by terminal status.",
    ["status"],
)
_SCHEDULER_MESSAGES_PUBLISHED = Counter(
    "sentiment_scheduler_messages_published_total",
    "Total generation messages published by the scheduler.",
)
_WORKER_MESSAGES = Counter(
    "sentiment_worker_messages_processed_total",
    "Total worker message executions by terminal status.",
    ["status"],
)
_WORKER_DURATION = Histogram(
    "sentiment_worker_processing_duration_seconds",
    "Worker processing duration in seconds by terminal status.",
    ["status"],
)
_QUEUE_PUBLISHED = Counter(
    "sentiment_queue_messages_published_total",
    "Total messages published to the queue backend.",
    ["backend"],
)
_INMEMORY_QUEUE_DEPTH = Gauge(
    "sentiment_inmemory_queue_depth_messages",
    "Current buffered message count for the in-memory queue backend.",
)
_LLM_CALLS = Counter(
    "sentiment_llm_calls_total",
    "Total LLM completion calls by pipeline, model, and terminal status.",
    ["pipeline", "model", "status"],
)
_LLM_DURATION = Histogram(
    "sentiment_llm_duration_seconds",
    "LLM completion call duration in seconds.",
    ["pipeline", "model", "status"],
)
_LLM_PROMPT_TOKENS = Counter(
    "sentiment_llm_prompt_tokens_total",
    "Total prompt tokens consumed by LLM calls.",
    ["pipeline", "model"],
)
_LLM_COMPLETION_TOKENS = Counter(
    "sentiment_llm_completion_tokens_total",
    "Total completion tokens generated by LLM calls.",
    ["pipeline", "model"],
)


def configure_telemetry() -> None:
    """Bootstrap OTel tracing and metrics providers.

    When ``settings.OTEL_ENABLED`` is ``False``, returns immediately so the
    SDK default no-op providers remain active.  No exporters or background
    threads are started.
    """
    global _tracer_provider, _meter_provider

    if not settings.OTEL_ENABLED:
        logger.info("telemetry_disabled")
        return

    resource = Resource.create(
        {ResourceAttributes.SERVICE_NAME: settings.OTEL_SERVICE_NAME}
    )

    _tracer_provider = _build_tracer_provider(resource)
    trace.set_tracer_provider(_tracer_provider)

    _meter_provider = _build_meter_provider(resource)
    metrics.set_meter_provider(_meter_provider)

    _instrument_libraries()

    set_global_textmap(TraceContextTextMapPropagator())

    logger.info(
        "telemetry_configured",
        service=settings.OTEL_SERVICE_NAME,
        endpoint=settings.OTEL_ENDPOINT,
    )


def shutdown_telemetry() -> None:
    """Flush and shut down OTel providers on application teardown.

    Safe to call even when telemetry is disabled; both providers will be
    ``None`` in that case and the function returns without error.
    """
    global _tracer_provider, _meter_provider

    if _tracer_provider is not None:
        _tracer_provider.shutdown()
        logger.info("telemetry_tracer_provider_shutdown")
        _tracer_provider = None

    if _meter_provider is not None:
        _meter_provider.shutdown()
        logger.info("telemetry_meter_provider_shutdown")
        _meter_provider = None


def register_metrics_endpoint(app: FastAPI) -> None:
    """Expose a Prometheus-compatible metrics endpoint on the application."""

    async def _metrics() -> Response:
        return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)

    app.add_api_route("/metrics", _metrics, methods=["GET"], include_in_schema=False)


def record_extraction_run(status: str, duration_seconds: float, saved_count: int = 0) -> None:
    """Record metrics for one extraction pipeline execution."""
    _EXTRACTION_REQUESTS.labels(status=status).inc()
    _EXTRACTION_DURATION.labels(status=status).observe(duration_seconds)
    if saved_count > 0:
        _EXTRACTION_TAGS_SAVED.inc(saved_count)


def record_generation_run(status: str, duration_seconds: float) -> None:
    """Record metrics for one generation pipeline execution."""
    _GENERATION_REQUESTS.labels(status=status).inc()
    _GENERATION_DURATION.labels(status=status).observe(duration_seconds)


def record_scheduler_run(status: str, duration_seconds: float, published_count: int) -> None:
    """Record metrics for one scheduler fan-out execution."""
    _SCHEDULER_RUNS.labels(status=status).inc()
    _SCHEDULER_DURATION.labels(status=status).observe(duration_seconds)
    if published_count > 0:
        _SCHEDULER_MESSAGES_PUBLISHED.inc(published_count)


def record_worker_run(status: str, duration_seconds: float) -> None:
    """Record metrics for one worker message execution."""
    _WORKER_MESSAGES.labels(status=status).inc()
    _WORKER_DURATION.labels(status=status).observe(duration_seconds)


def record_queue_publish(backend: str) -> None:
    """Increment the publish counter for the selected queue backend."""
    _QUEUE_PUBLISHED.labels(backend=backend).inc()


def set_inmemory_queue_depth(depth: int) -> None:
    """Track current in-memory queue buffer size."""
    _INMEMORY_QUEUE_DEPTH.set(depth)


def record_llm_metrics(
    pipeline: str,
    model: str,
    status: str,
    duration_seconds: float,
    prompt_tokens: int | None,
    completion_tokens: int | None,
) -> None:
    """Record Prometheus metrics for one LLM completion call.

    Args:
        pipeline: Pipeline name (``"extraction"`` or ``"generation"``).
        model: Ollama model identifier.
        status: ``"success"`` or ``"error"``.
        duration_seconds: LLM call duration (``LLMResult.latency_ms / 1000``).
        prompt_tokens: Prompt tokens consumed; ``None`` if unavailable.
        completion_tokens: Completion tokens generated; ``None`` if unavailable.
    """
    _LLM_CALLS.labels(pipeline=pipeline, model=model, status=status).inc()
    _LLM_DURATION.labels(pipeline=pipeline, model=model, status=status).observe(duration_seconds)
    if prompt_tokens is not None:
        _LLM_PROMPT_TOKENS.labels(pipeline=pipeline, model=model).inc(prompt_tokens)
    if completion_tokens is not None:
        _LLM_COMPLETION_TOKENS.labels(pipeline=pipeline, model=model).inc(completion_tokens)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _build_tracer_provider(resource: Resource) -> TracerProvider:
    """Build a TracerProvider with a BatchSpanProcessor backed by OTLP HTTP.

    Args:
        resource: OTel Resource describing this service instance.

    Returns:
        A configured TracerProvider ready to be set as the global provider.
    """
    from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter  # type: ignore[import-not-found]

    exporter = OTLPSpanExporter(endpoint=f"{settings.OTEL_ENDPOINT}/v1/traces")
    provider = TracerProvider(resource=resource)
    provider.add_span_processor(BatchSpanProcessor(exporter))
    return provider


def _build_meter_provider(resource: Resource) -> MeterProvider:
    """Build a MeterProvider with a PeriodicExportingMetricReader backed by OTLP HTTP.

    Args:
        resource: OTel Resource describing this service instance.

    Returns:
        A configured MeterProvider ready to be set as the global provider.
    """
    from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter  # type: ignore[import-not-found]

    exporter = OTLPMetricExporter(endpoint=f"{settings.OTEL_ENDPOINT}/v1/metrics")
    reader = PeriodicExportingMetricReader(exporter)
    return MeterProvider(resource=resource, metric_readers=[reader])


def _instrument_libraries() -> None:
    """Apply automatic instrumentation for FastAPI, httpx, and SQLAlchemy.

    Each instrumentor guards against double-instrumentation internally, so
    calling this function more than once (e.g., in tests) is safe and will
    not register duplicate spans or metrics.
    """
    from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor  # type: ignore[import-not-found]
    from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor  # type: ignore[import-not-found]
    from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor  # type: ignore[import-not-found]

    FastAPIInstrumentor().instrument()
    HTTPXClientInstrumentor().instrument()
    SQLAlchemyInstrumentor().instrument()

    logger.info(
        "telemetry_instrumentation_applied",
        libraries=["fastapi", "httpx", "sqlalchemy"],
    )
